### ISSUE TITLE
增加可用性

### ISSUE THREAD

**Issue by childeyouyu** [x-dr/tts#2]
能否使用接口进行批量语音合成？或是开放导入文本进行批量合成的功能

**Comment by x-dr** [comment]
这只是一个白嫖[cloudflare](https://dash.cloudflare.com/)简单的小demo ,如果想批量合成可参考[api/tts.js](https://github.com/x-dr/tts/blob/main/api/tts.js) 改写

**Comment by ALEXuH** [comment]
> 能否使用接口进行批量语音合成？或是开放导入文本进行批量合成的功能

https://www.ttson.cn/ 可以试试这个
